from .accountSerializer import AccountSerializer
from .userSerializer import UserSerializer
from .EntidadesSerializer import EntidadesSerializer
from .medicamentosSerializer import MedicamentosSerializer
from .LaboratoriosSerializer import LaboratoriosSerializer