from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .LaboratorioCreateView import Laboratorios_api_view
from .LaboratorioCreateView import Laboratorios_detalle_api_view
from .ConsecutivosCreateView import consecutivo_api_view
from .ConsecutivosCreateView import consecutivo_detalle_api_view
from .EntidadesCreateView import entidad_api_view
from .EntidadesCreateView import entidad_detalle_api_view
from .FormaFarmaceuticaCreateView import FormaFarmaceutica_api_view
from .FormaFarmaceuticaCreateView import FormaFarmaceutica_detalle_api_view
from .GrupoFarmacologicoCreateView import Grupo_Farmacologico_api_view
from .GrupoFarmacologicoCreateView import Grupo_Farmacologico_detalle_api_view
from .PacientesCreateView import Pacientes_api_view
from .PacientesCreateView import Pacientes_detalle_api_view
from .PresentacionCreateView import Presentacion_api_view
from .PresentacionCreateView import Presentacion_detalle_api_view
from .ProfesionalesCreateView import Profesionales_api_view
from .ProfesionalesCreateView import Profesionales_detalle_api_view
from .SistemaOrganicoCreateView import Sistema_Organico_api_view
from .SistemaOrganicoCreateView import Sistema_Organico_detalle_api_view
from .SubGrupo_FarmacologicoCreateView import Subgrupo_Farmacologico_api_view
from .SubGrupo_FarmacologicoCreateView import Subgrupo_Farmacologico_detalle_api_view
from .SubGrupo_QuimicoCreateView import Subgrupo_Quimico_api_view
from .SubGrupo_QuimicoCreateView import Subgrupo_Quimico_detalle_api_view
from .medicamentosCreateView import Medicamentos_api_view
from .medicamentosCreateView import Medicamentos_detalle_api_view
from .genericosCreateView import Genericos_api_view
from .genericosCreateView import Genericos_detalle_api_view
from .formulaencabezadoCreateView import FormulaEncabezado_api_view
from .formulaencabezadoCreateView import FormulaEncabezado_detalle_api_view
from .formuladetalleCreateView import FormulaDetalle_api_view
from .formuladetalleCreateView import FormulaDetalle_detalle_api_view



