# Generated by Django 3.2.7 on 2021-11-21 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivos',
            fields=[
                ('id_Consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_Inicial', models.IntegerField(verbose_name='Numero_Inicial')),
                ('Numero_Final', models.IntegerField(verbose_name='Numero_Final')),
            ],
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id_Entidad', models.AutoField(primary_key=True, serialize=False)),
                ('Razon_social', models.CharField(max_length=256, verbose_name='Entidades')),
            ],
        ),
        migrations.CreateModel(
            name='FormaFamaceutica',
            fields=[
                ('id_FormaFamaceutica', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id_FormaFamaceutica')),
                ('FormaFamaceutica', models.CharField(max_length=256, verbose_name='FormaFamaceutica')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Farmacologico',
            fields=[
                ('id_Grupo_Farmacologico', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='id_GrupoFarmacologico')),
                ('Grupo_Farmacologico', models.CharField(max_length=256, verbose_name='GrupoFarmacologico')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id_Laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('Laboratorio', models.CharField(max_length=256, verbose_name='Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_Presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('Presentacion', models.CharField(max_length=256, verbose_name='Presentacion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('Registro_Medico', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Registro_Medico')),
                ('Tipodoc', models.CharField(max_length=3, verbose_name='TipoDoc')),
                ('IdDocumento', models.CharField(max_length=30, verbose_name='IDDocumento')),
                ('Pname', models.CharField(max_length=30, verbose_name='PName')),
                ('sname', models.CharField(max_length=30, verbose_name='SName')),
                ('Papellido', models.CharField(max_length=30, verbose_name='PApellido')),
                ('Sapellido', models.CharField(max_length=30, verbose_name='SApellido')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_Organico',
            fields=[
                ('id_Sistema_Organico', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='id_SistemaOrganico ')),
                ('Sistema_Organico', models.CharField(max_length=256, verbose_name='Sistema_Organico')),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo_Farmacologico',
            fields=[
                ('id_SubgrupoFarmacologico', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='id_SubgrupoFarmacologico')),
                ('Subgrupo_Farmacologico', models.CharField(max_length=256, verbose_name='Subgrupo_Farmacologico')),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo_Quimico',
            fields=[
                ('id_Subgrupo_Quimico', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='id_SubgrupoQuimico')),
                ('Subgrupo_Quimico', models.CharField(max_length=256, verbose_name='Subgrupo_Quimico')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('Pname', models.CharField(max_length=30, verbose_name='PName')),
                ('sname', models.CharField(max_length=30, verbose_name='SName')),
                ('Papellido', models.CharField(max_length=30, verbose_name='PApellido')),
                ('Sapellido', models.CharField(max_length=30, verbose_name='SApellido')),
                ('Tipodoc', models.CharField(max_length=3, verbose_name='TipoDoc')),
                ('IdDocumento', models.CharField(max_length=30, verbose_name='IDDocumento')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('Cod_Paciente', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cod_Paciente')),
                ('Tipodoc', models.CharField(max_length=3, verbose_name='TipoDoc')),
                ('IdDocumento', models.CharField(max_length=30, verbose_name='IDDocumento')),
                ('Pname', models.CharField(max_length=30, verbose_name='PName')),
                ('sname', models.CharField(max_length=30, verbose_name='SName')),
                ('Papellido', models.CharField(max_length=30, verbose_name='PApellido')),
                ('Sapellido', models.CharField(max_length=30, verbose_name='SApellido')),
                ('id_Entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pacientes', to='PharmaWeb.entidades')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_Medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('Medicamento', models.CharField(max_length=256, verbose_name='Medicamento')),
                ('Existencia', models.IntegerField(verbose_name='Existencia')),
                ('id_Laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Genericos',
            fields=[
                ('id_Generico', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='id_Generico')),
                ('Genericos', models.CharField(max_length=256, verbose_name='Genericos')),
                ('id_FormaFamaceutica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genericos', to='PharmaWeb.formafamaceutica')),
                ('id_Grupo_Farmacologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genericos', to='PharmaWeb.grupo_farmacologico')),
                ('id_Sistema_Organico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genericos', to='PharmaWeb.sistema_organico')),
                ('id_SubgrupoFarmacologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genericos', to='PharmaWeb.subgrupo_farmacologico')),
                ('id_Subgrupo_Quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genericos', to='PharmaWeb.subgrupo_quimico')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaEncabezado',
            fields=[
                ('id_Formula_Encabezado', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Formula', models.DateField(max_length=10, verbose_name='Fecha_Formula')),
                ('Cod_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formula_Encabezado', to='PharmaWeb.pacientes')),
                ('Registro_Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formula_Encabezado', to='PharmaWeb.profesionales')),
                ('id_Consecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formula_Encabezado', to='PharmaWeb.consecutivos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formula_Encabezado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaDetalle',
            fields=[
                ('id_Formula_Detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('id_Formula_Encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formula_Detalle', to='PharmaWeb.formulaencabezado')),
                ('id_Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formula_Detalle', to='PharmaWeb.medicamentos')),
            ],
        ),
        migrations.AddField(
            model_name='consecutivos',
            name='id_Entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consecutivos', to='PharmaWeb.entidades'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
